"""
This type stub file was generated by pyright.
"""

import sys

'''
Fixes code like the 2to3 Python utility, but with fixers from the local fixes
directory.

(c) 2013 by Eric O. LEBIGOT (EOL).
'''
if sys.version_info < (2, 6):
    ...
