"""
This type stub file was generated by pyright.
"""

_TAG_VALUE_ERROR = ...
class TagValue(str):
    """The value of a tag"""
    def __new__(cls, value): # -> Self@TagValue:
        """Create and return a new tag value

        :type value: str
        :param value: A string representing the value of a key in a tag
        :return: TagValue
        """
        ...
    


