"""
This type stub file was generated by pyright.
"""

def is_legal_chars(value): # -> bool:
    ...

def is_valid_tag_name(name): # -> bool:
    """Checks if the name of a tag key is valid

    :type name: str
    :param name: name to check

    :rtype: bool
    :returns: True if it valid, else returns False
    """
    ...

def is_valid_tag_value(value): # -> bool:
    """Checks if the value is valid

    :type value: str
    :param value: the value to be checked

    :rtype: bool
    :returns: True if valid, if not, False.

    """
    ...

