"""
This type stub file was generated by pyright.
"""

Tag_ = ...
class Tag(Tag_):
    """A tag, in the format [KEY]:[VALUE].

    :type key: str
    :param key: The name of the tag

    :type value: str
    :param value: The value of the tag

    """
    def __new__(cls, key, value): # -> Self@Tag:
        ...
    


