"""
This type stub file was generated by pyright.
"""

_TAG_NAME_ERROR = ...
class TagKey(str):
    """A tag key with a property name"""
    def __new__(cls, name): # -> Self@TagKey:
        """Create and return a new tag key

        :type name: str
        :param name: The name of the key
        :return: TagKey
        """
        ...
    


