"""
This type stub file was generated by pyright.
"""

from opencensus.metrics.export.metric_producer import MetricProducer

_STATSBEAT_METRICS = ...
_STATSBEAT_EXPORTER = ...
_STATSBEAT_LOCK = ...
def collect_statsbeat_metrics(options): # -> None:
    ...

def shutdown_statsbeat_metrics(): # -> None:
    ...

class _AzureStatsbeatMetricsProducer(MetricProducer):
    """Implementation of the producer of statsbeat metrics.

    Includes Azure attach rate, network and feature metrics,
    implemented using gauges.
    """
    def __init__(self, options) -> None:
        ...
    
    def get_metrics(self): # -> list[Unknown]:
        ...
    
    def get_initial_metrics(self): # -> list[Unknown]:
        ...
    


