"""
This type stub file was generated by pyright.
"""

from opencensus.ext.azure.metrics_exporter.standard_metrics.cpu import ProcessorTimeMetric
from opencensus.ext.azure.metrics_exporter.standard_metrics.http_requests import RequestsAvgExecutionMetric, RequestsRateMetric
from opencensus.ext.azure.metrics_exporter.standard_metrics.memory import AvailableMemoryMetric
from opencensus.ext.azure.metrics_exporter.standard_metrics.process import ProcessCPUMetric, ProcessMemoryMetric
from opencensus.metrics.export.gauge import Registry
from opencensus.metrics.export.metric_producer import MetricProducer

STANDARD_METRICS = ...
def register_metrics(): # -> Registry:
    ...

class AzureStandardMetricsProducer(MetricProducer):
    """Implementation of the producer of standard metrics.

    Includes Azure specific standard metrics, implemented
    using gauges.
    """
    def __init__(self) -> None:
        ...
    
    def get_metrics(self): # -> set[Unknown]:
        ...
    


producer = ...
