"""
This type stub file was generated by pyright.
"""

logger = ...
PROCESS = ...
class ProcessMemoryMetric:
    NAME = ...
    @staticmethod
    def get_value(): # -> Any | None:
        ...
    
    def __call__(self): # -> DerivedLongGauge:
        """ Returns a derived gauge for private bytes for the current process

        Private bytes for the current process is measured by the Resident Set
        Size, which is the non-swapped physical memory a process has used.

        :rtype: :class:`opencensus.metrics.export.gauge.DerivedLongGauge`
        :return: The gauge representing the private bytes metric
        """
        ...
    


class ProcessCPUMetric:
    NAME = ...
    @staticmethod
    def get_value(): # -> float | None:
        ...
    
    def __call__(self): # -> DerivedDoubleGauge:
        """ Returns a derived gauge for the CPU usage for the current process.
        Return values range from 0.0 to 100.0 inclusive.
        :rtype: :class:`opencensus.metrics.export.gauge.DerivedDoubleGauge`
        :return: The gauge representing the process cpu usage metric
        """
        ...
    


