"""
This type stub file was generated by pyright.
"""

"""
This module provides uncertainty-aware functions that generalize some
of the functions from numpy.linalg.

(c) 2010-2016 by Eric O. LEBIGOT (EOL) <eric.lebigot@normalesup.org>.
"""
__all__ = ['inv', 'pinv']
