"""
This type stub file was generated by pyright.
"""

_measure_to_view_map_slot = ...
def get_measure_to_view_map():
    ...

def set_measure_to_view_map(measure_to_view_map): # -> None:
    ...

def clear(): # -> None:
    """Clear the context, used in test."""
    ...

