"""
This type stub file was generated by pyright.
"""

class ViewManager:
    """View Manager allows the registering of Views for collecting stats
    and receiving stats data as View Data"""
    def __init__(self) -> None:
        ...
    
    @property
    def measure_to_view_map(self):
        """the current measure to view map for the View Manager"""
        ...
    
    def register_view(self, view): # -> None:
        """registers the given view"""
        ...
    
    def get_view(self, view_name):
        """gets the view given the view name """
        ...
    
    def get_all_exported_views(self):
        """returns all of the exported views for the current measure to view
        map"""
        ...
    
    def register_exporter(self, exporter): # -> None:
        """register the exporter"""
        ...
    
    def unregister_exporter(self, exporter): # -> None:
        """unregister the exporter"""
        ...
    


