"""
This type stub file was generated by pyright.
"""

"""
Standar HID usage page definitions
"""
class UsagePage:
    """Translate usage name between numeric and string values.
    So, str() or int() can be applied to get desired value
    """
    __usage_map_string_keys = ...
    __usage_map_number_keys = ...
    __range_usages = ...
    def __init__(self, page) -> None:
        ...
    
    def __int__(self) -> int:
        ...
    
    def __str__(self) -> str:
        ...
    


class HidUsage:
    """\
    usage tables
    done finding regex:
        ^0*\([0-9\-a-fA-F]+\)\( \)\(\D*\)\( .*\)\( \d+\.\d+\)$
        ^0*\([0-9\-a-fA-F]+\)\( \)\(\D*\)\( .*\)\( \d+\.\d+\.*\d*\)$
    and replacing by:
        0x\1: ("\3", \4),
    """
    Usages = ...
    def __init__(self, page_id, usage_id) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


if __name__ == '__main__':
    PAGES = ...
