"""
This type stub file was generated by pyright.
"""

import os
from ._version import __jupyter_widgets_base_version__, __jupyter_widgets_controls_version__, __protocol_version__, __version__
from IPython import get_ipython
from .widgets import *
from traitlets import dlink, link

"""Interactive widgets for the Jupyter notebook.

Provide simple interactive controls in the notebook.
Each Widget corresponds to an object in Python and Javascript,
with controls on the page.

To put a Widget on the page, you can display it with Jupyter's display machinery::

    from ipywidgets import IntSlider
    slider = IntSlider(min=1, max=10)
    display(slider)

Moving the slider will change the value. Most Widgets have a current value,
accessible as a `value` attribute.
"""
def load_ipython_extension(ip): # -> None:
    """Set up Jupyter to work with widgets"""
    ...

def register_comm_target(kernel=...): # -> None:
    """Register the jupyter.widget comm target"""
    ...

__all__ = ["Accordion",
 "AppLayout",
 "Audio",
 "BoundedFloatText",
 "BoundedIntText",
 "Box",
 "Button",
 "ButtonStyle",
 "CallbackDispatcher",
 "Checkbox",
 "Color",
 "ColorPicker",
 "ColorsInput",
 "Combobox",
 "Controller",
 "CoreWidget",
 "DOMWidget",
 "DatePicker",
 "Datetime",
 "DatetimePicker",
 "Dropdown",
 "FileUpload",
 "FloatLogSlider",
 "FloatProgress",
 "FloatRangeSlider",
 "FloatSlider",
 "FloatText",
 "FloatsInput",
 "GridBox",
 "GridspecLayout",
 "HBox",
 "HTML",
 "HTMLMath",
 "Image",
 "IntProgress",
 "IntRangeSlider",
 "IntSlider",
 "IntText",
 "IntsInput",
 "Label",
 "Layout",
 "NaiveDatetimePicker",
 "NumberFormat",
 "Output",
 "Password",
 "Play",
 "RadioButtons",
 "Select",
 "SelectMultiple",
 "SelectionRangeSlider",
 "SelectionSlider",
 "SliderStyle",
 "Stack",
 "Style",
 "Tab",
 "TagsInput",
 "Text",
 "Textarea",
 "TimePicker",
 "ToggleButton",
 "ToggleButtons",
 "ToggleButtonsStyle",
 "TwoByTwoLayout",
 "TypedTuple",
 "VBox",
 "Valid",
 "ValueWidget",
 "Video",
 "Widget",
 "fixed",
 "interact",
 "interact_manual",
 "interactive",
 "interactive_output",
 "jsdlink",
 "jslink",
 "register",
 "widget_serialization",]