"""
This type stub file was generated by pyright.
"""

class LabelValue:
    """The label values associated with the TimeSeries.

    :type value: str
    :param value: the value for the label
    """
    def __init__(self, value=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def value(self): # -> None:
        """the value for the label"""
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    


