"""
This type stub file was generated by pyright.
"""

class Type:
    """The relationship of the current span relative to the linked span: child,
    parent, or unspecified.

    Attributes:
      TYPE_UNSPECIFIED (int): The relationship of the two spans is unknown.
      CHILD_LINKED_SPAN (int): The linked span is a child of the current span.
      PARENT_LINKED_SPAN (int): The linked span is a parent of the current
      span.
    """
    TYPE_UNSPECIFIED = ...
    CHILD_LINKED_SPAN = ...
    PARENT_LINKED_SPAN = ...


class Link:
    """A pointer from the current span to another span in the same trace or in
    a different trace. For example, this can be used in batching operations,
    where a single batch handler processes multiple requests from different
    traces or when the handler receives a request from a different project.

    :type trace_id: str
    :param trace_id: The [TRACE_ID] for a trace within a project.

    :type span_id: str
    :param span_id: The [SPAN_ID] for a span within a trace.

    :type type: Enum of :class:`~opencensus.trace.link.Type`
    :param type: The relationship of the current span relative to the linked
                 span.

    :type attributes: :class:`~opencensus.trace.attributes.Attributes`
    :param attributes: A set of attributes on the link. You have have up to 32
                       attributes per link.
    """
    def __init__(self, trace_id, span_id, type=..., attributes=...) -> None:
        ...
    
    def format_link_json(self): # -> dict[Unknown, Unknown]:
        """Convert a Link object to json format."""
        ...
    


