"""
This type stub file was generated by pyright.
"""

class BaseObject(dict):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    def __getattr__(self, name):
        ...
    
    def __getitem__(self, key):
        ...
    


class Data(BaseObject):
    _default = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class DataPoint(BaseObject):
    _default = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class Envelope(BaseObject):
    _default = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class Event(BaseObject):
    _default = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class ExceptionData(BaseObject):
    _default = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class Message(BaseObject):
    _default = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class MetricData(BaseObject):
    _default = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class RemoteDependency(BaseObject):
    _default = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class Request(BaseObject):
    _default = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


