"""
This type stub file was generated by pyright.
"""

class Metric:
    """A collection of time series data and label metadata.

    This class implements the spec for v1 Metrics as of opencensus-proto
    release v0.1.0. See opencensus-proto for details:

    https://github.com/census-instrumentation/opencensus-proto/blob/v0.1.0/src/opencensus/proto/metrics/v1/metrics.proto#L35

    Defines a Metric which has one or more timeseries.

    :type descriptor: class: '~opencensus.metrics.export.metric_descriptor.MetricDescriptor'
    :param descriptor: The metric's descriptor.

    :type timeseries: list(:class: '~opencensus.metrics.export.time_series.TimeSeries')
    :param timeseries: One or more timeseries for a single metric, where each
    timeseries has one or more points.
    """
    def __init__(self, descriptor, time_series) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def time_series(self): # -> Unknown:
        ...
    
    @property
    def descriptor(self):
        ...
    


