"""
This type stub file was generated by pyright.
"""

class Point:
    """A timestamped measurement of a TimeSeries.

    :type value: :class:`opencensus.metrics.export.value.ValueDouble` or
        :class:`opencensus.metrics.export.value.ValueLong` or
        :class:`opencensus.metrics.export.value.ValueSummary` or
        :class:`opencensus.metrics.export.value.ValueDistribution`
    :param value: the point value.

    :type timestamp: time
    :param timestamp: the timestamp when the `Point` was recorded.
    """
    def __init__(self, value, timestamp) -> None:
        ...
    
    @property
    def value(self): # -> Unknown:
        ...
    
    @property
    def timestamp(self): # -> Unknown:
        ...
    
    def __repr__(self): # -> str:
        ...
    


