"""
This type stub file was generated by pyright.
"""

class TimeSeries:
    """Time series data for a given metric and time interval.

    This class implements the spec for v1 TimeSeries structs as of
    opencensus-proto release v0.1.0. See opencensus-proto for details:

        https://github.com/census-instrumentation/opencensus-proto/blob/v0.1.0/src/opencensus/proto/metrics/v1/metrics.proto#L132

    A TimeSeries is a collection of data points that describes the time-varying
    values of a metric.

    :type label_values: list(:class:
    '~opencensus.metrics.label_value.LabelValue')
    :param label_values: The set of label values that uniquely identify this
    timeseries.

    :type points: list(:class: '~opencensus.metrics.export.point.Point')
    :param points: The data points of this timeseries.

    :type start_timestamp: str
    :param start_timestamp: The time when the cumulative value was reset to
    zero, must be set for cumulative metrics.
    """
    def __init__(self, label_values, points, start_timestamp) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def start_timestamp(self): # -> Unknown:
        ...
    
    @property
    def label_values(self):
        ...
    
    @property
    def points(self): # -> Unknown:
        ...
    
    def check_points_type(self, type_class): # -> bool:
        """Check that each point's value is an instance of `type_class`.

        `type_class` should typically be a Value type, i.e. one that extends
        :class: `opencensus.metrics.export.value.Value`.

        :type type_class: type
        :param type_class: Type to check against.

        :rtype: bool
        :return: Whether all points are instances of `type_class`.
        """
        ...
    


