"""
This type stub file was generated by pyright.
"""

import six
import weakref

class WeakMethod(weakref.ref):
    """
    A custom `weakref.ref` subclass which simulates a weak reference to
    a bound method, working around the lifetime problem of bound methods.

    This is a copy of the WeakMethod class that ships with weakref in the
    python 3.7 standard library, adapted to work in 2.6. See:
    https://github.com/python/cpython/blob/a31f4cc881992e84d351957bd9ac1a92f882fa39/Lib/weakref.py#L36-L87
    """
    __slots__ = ...
    def __new__(cls, meth, callback=...): # -> Self@WeakMethod:
        ...
    
    def __call__(self): # -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    __hash__ = ...


