"""
This type stub file was generated by pyright.
"""

from .core import CompatibilityError, Dimension, File, Group, Variable

"""
h5netcdf
========

A Python library for the netCDF4 file-format that directly reads and writes
HDF5 files via h5py, without using the Unidata netCDF library.
"""
