"""
This type stub file was generated by pyright.
"""

from collections.abc import MutableMapping

class Dimensions(MutableMapping):
    def __init__(self, group) -> None:
        ...
    
    def __getitem__(self, name):
        ...
    
    def __setitem__(self, name, size): # -> None:
        ...
    
    def add_phony(self, name, size): # -> None:
        ...
    
    def add(self, name): # -> None:
        ...
    
    def __delitem__(self, key):
        ...
    
    def __iter__(self): # -> Generator[Unknown, None, None]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __repr__(self): # -> LiteralString | Literal['<Closed h5netcdf.Dimensions>']:
        ...
    


class Dimension:
    def __init__(self, parent, name, size=..., create_h5ds=..., phony=...) -> None:
        """NetCDF4 Dimension constructor.

        Parameters
        ----------
        parent: h5netcdf.Group
            Parent group.
        name: str
            Name of the dimension.
        size : int
            Size of the Netcdf4 Dimension. Defaults to None (unlimited).
        create_h5ds : bool
            For internal use only.
        phony : bool
            For internal use only.
        """
        ...
    
    @property
    def name(self): # -> Unknown:
        """Return dimension name."""
        ...
    
    @property
    def size(self): # -> int:
        """Return dimension size."""
        ...
    
    def group(self): # -> Unknown | None:
        """Return parent group."""
        ...
    
    def isunlimited(self): # -> Literal[False]:
        """Return ``True`` if dimension is unlimited, otherwise ``False``."""
        ...
    
    def __len__(self): # -> int:
        ...
    
    _cls_name = ...
    def __repr__(self): # -> str:
        ...
    


