"""
This type stub file was generated by pyright.
"""

from . import core

default_fillvals = ...
class HasAttributesMixin:
    _initialized = ...
    def getncattr(self, name):
        """Retrieve a netCDF4 attribute."""
        ...
    
    def setncattr(self, name, value): # -> None:
        """Set a netCDF4 attribute."""
        ...
    
    def ncattrs(self): # -> list[Unknown]:
        """Return netCDF4 attribute names."""
        ...
    
    def __getattr__(self, name):
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    


class Variable(core.BaseVariable, HasAttributesMixin):
    _cls_name = ...
    def chunking(self): # -> Literal['contiguous']:
        """Return variable chunking information.

        The chunksize is returned as a sequence with the size for each dimension.
        If the dataset is defined to be contiguous (no chunking) the word 'contiguous'
        is returned.
        """
        ...
    
    def filters(self): # -> dict[str, Unknown]:
        """Return HDF5 filter parameters dictionary."""
        ...
    
    @property
    def dtype(self): # -> Type[str]:
        """Return netCDF4.Variable datatype."""
        ...
    


class Group(core.Group, HasAttributesMixin):
    _cls_name = ...
    _variable_cls = Variable
    createGroup = ...
    def createDimension(self, name, size):
        """Creates a new dimension with given name and size.

        Parameters
        ----------
        name : str
            Dimension name
        size : int, None
            size must be a positive integer or None (unlimited).
            Specifying size=0 results in an unlimited dimension too.

        Returns
        -------
        dim : h5netcdf.legacyapi.Dimension
            Dimension class instance.
        """
        ...
    
    def createVariable(self, varname, datatype, dimensions=..., zlib=..., complevel=..., shuffle=..., fletcher32=..., chunksizes=..., fill_value=..., endian=...):
        """Creates a new variable.

        Parameters
        ----------
        varname : str
            Name of the new variable. If given as a path, intermediate groups will be created,
            if not existent.
        datatype : numpy.dtype, str
            Dataype of the new variable
        dimensions : tuple
            Tuple containing dimension name strings. Defaults to empty tuple, effectively
            creating a scalar variable.
        zlib : bool, optional
            If ``True``, variable data will be gzip compressed.
        complevel : int, optional
            Integer between 1 and 9 defining compression level. Defaults to 4.
            Ignored if ``zlib=False``.
        shuffle : bool, optional
            If ``True``, HDF5 shuffle filter will be applied. Defaults to ``True``.
            Ignored if ``zlib=False``.
        fletcher32 : bool, optional
            If ``True``, HDF5 Fletcher32 checksum algorithm is applied. Defaults to ``False``.
        chunksizes : tuple, optional
            Tuple of integers specifying the chunksizes of each variable dimension.
            Discussion on ``h5netcdf`` chunksizes can be found in (:issue:`52`) and (:pull:`127`).
        fill_value : scalar, optional
            Specify ``_FillValue`` for uninitialized parts of the variable. Defaults to ``None``.
        endian : str, optional
            Control on-disk storage format.
            Can be any of ``little``, ``big`` or ``native`` (default).

        Returns
        -------
        var : h5netcdf.legacyapi.Variable
            Variable class instance
        """
        ...
    


class Dimension(core.Dimension):
    _cls_name = ...


class Dataset(core.File, Group, HasAttributesMixin):
    _cls_name = ...


