"""
This type stub file was generated by pyright.
"""

class LabelKey:
    """The label keys associated with the metric descriptor.

    :type key: str
    :param key: the key for the label

    :type description: str
    :param description: description of the label
    """
    def __init__(self, key, description) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def key(self): # -> Unknown:
        """the key for the label"""
        ...
    
    @property
    def description(self): # -> Unknown:
        """a human-readable description of what this label key represents"""
        ...
    


