"""
This type stub file was generated by pyright.
"""

class StatsRecorder:
    """Stats Recorder provides methods to record stats against tags

    """
    def __init__(self) -> None:
        ...
    
    def new_measurement_map(self): # -> MeasurementMap:
        """Creates a new MeasurementMap in order to record stats
        :returns a MeasurementMap for recording multiple measurements
        """
        ...
    


