"""
This type stub file was generated by pyright.
"""

class ViewData:
    """View Data is the aggregated data for a particular view

    :type view:
    :param view: The view associated with this view data

    :type start_time: datetime
    :param start_time: the start time for this view data

    :type end_time: datetime
    :param end_time: the end time for this view data

    """
    def __init__(self, view, start_time, end_time) -> None:
        ...
    
    @property
    def view(self): # -> Unknown:
        """the current view in the view data"""
        ...
    
    @property
    def start_time(self): # -> Unknown | str:
        """the current start time in the view data"""
        ...
    
    @property
    def end_time(self): # -> Unknown | str:
        """the current end time in the view data"""
        ...
    
    @property
    def tag_value_aggregation_data_map(self): # -> dict[Unknown, Unknown]:
        """the current tag value aggregation map in the view data"""
        ...
    
    def start(self): # -> None:
        """sets the start time for the view data"""
        ...
    
    def end(self): # -> None:
        """sets the end time for the view data"""
        ...
    
    def get_tag_values(self, tags, columns): # -> list[Unknown]:
        """function to get the tag values from tags and columns"""
        ...
    
    def record(self, context, value, timestamp, attachments=...): # -> None:
        """records the view data against context"""
        ...
    


