"""
This type stub file was generated by pyright.
"""

class Attributes:
    """A set of attributes, each in the format [KEY]:[VALUE].

    :type attributes: dict
    :param attributes: The set of attributes. Each attribute's key can be up
                       to 128 bytes long. The value can be a string up to 256
                       bytes, an integer, a floating-point number, or the
                       Boolean values true and false.
    """
    def __init__(self, attributes=...) -> None:
        ...
    
    def set_attribute(self, key, value): # -> None:
        """Set a key value pair."""
        ...
    
    def delete_attribute(self, key): # -> None:
        """Delete an attribute given a key if existed."""
        ...
    
    def get_attribute(self, key): # -> Any | None:
        """Get a attribute value."""
        ...
    
    def format_attributes_json(self): # -> dict[str, dict[Unknown, Unknown]]:
        """Convert the Attributes object to json format."""
        ...
    


