"""
This type stub file was generated by pyright.
"""

_ENABLED_BITMASK = ...
DEFAULT = ...
class TraceOptions:
    """A class that represents global trace options.

    :type trace_options_byte: str
    :param trace_options_byte: 1 byte bitmap for trace options.
    """
    def __init__(self, trace_options_byte=...) -> None:
        ...
    
    def check_trace_options(self, trace_options_byte): # -> Literal['1']:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def get_enabled(self): # -> bool:
        """Get the last bit from the trace options which is the enabled field.

        :type trace_options: byte
        :param trace_options: 1 byte field which indicates 8 trace options,
                              currently only have the enabled option. 1 means
                              enabled, 0 means not enabled.

        :rtype: bool
        :returns: Enabled tracing or not.
        """
        ...
    
    def set_enabled(self, enabled): # -> None:
        """Update the last bit of the trace options byte str.

        :type enabled: bool
        :param enabled: Whether enable tracing in this span context or not.
        """
        ...
    


