"""
This type stub file was generated by pyright.
"""

logger = ...
class LocalFileBlob:
    def __init__(self, fullpath) -> None:
        ...
    
    def delete(self): # -> None:
        ...
    
    def get(self): # -> tuple[Any, ...] | None:
        ...
    
    def put(self, data, lease_period=...): # -> Self@LocalFileBlob | None:
        ...
    
    def lease(self, period): # -> Self@LocalFileBlob | None:
        ...
    


class LocalFileStorage:
    def __init__(self, path, max_size=..., maintenance_period=..., retention_period=..., write_timeout=..., source=...) -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def __enter__(self): # -> Self@LocalFileStorage:
        ...
    
    def __exit__(self, type, value, traceback): # -> None:
        ...
    
    def gets(self): # -> Generator[LocalFileBlob, None, None]:
        ...
    
    def get(self): # -> LocalFileBlob | None:
        ...
    
    def put(self, data, lease_period=...): # -> LocalFileBlob | None:
        ...
    


