"""
This type stub file was generated by pyright.
"""

"""
Other helper functions.
"""
def write_documentation(self, output_file): # -> None:
    "Issue documentation report on output_file file like object"
    class CompundVarDict:
        """Compound variables dictionary.
        Keys are strings mapping variables.
        If any string has a '.' on it, it means that is an
        object with an attribute. The attribute name will be
        used then as the returned item value.
        """
        ...
    
    

