"""
This type stub file was generated by pyright.
"""

import platform

"""
This is a modification of the original WndProcHookMixin by Kevin Moore,
modified to use ctypes only instead of pywin32, so it can be used with no
additional dependencies in Python 2.5
"""
CallWindowProc = ...
if platform.architecture()[0].startswith('64'):
    SetWindowLong = ...
else:
    SetWindowLong = ...
GWL_WNDPROC = ...
WM_DESTROY = ...
if platform.architecture()[0].startswith('64'):
    WndProcType = ...
else:
    WndProcType = ...
class WndProcHookMixin:
    """
    This class can be mixed in with any window class in order to hook it's
    WndProc function.  You supply a set of message handler functions with the
    function add_msg_handler. When the window receives that message, the
    specified handler function is invoked. If the handler explicitly returns
    False then the standard WindowProc will not be invoked with the message.
    You can really screw things up this way, so be careful.  This is not the
    correct way to deal with standard windows messages in wxPython (i.e. button
    click, paint, etc) use the standard wxWindows method of binding events for
    that. This is really for capturing custom windows messages or windows
    messages that are outside of the wxWindows world.
    """
    def __init__(self, wnd_handle) -> None:
        ...
    
    def hook_wnd_proc(self): # -> None:
        """Attach to OS Window message handler"""
        ...
    
    def unhook_wnd_proc(self): # -> None:
        """Restore previous Window message handler"""
        ...
    
    def add_msg_handler(self, message_number, handler): # -> None:
        """Add custom handler function to specific OS message number"""
        ...
    
    def local_wnd_proc(self, h_wnd, msg, w_param, l_param): # -> Any | None:
        """
        Call the handler if one exists.
        """
        ...
    


if __name__ == "__main__":
    def demo_module(): # -> None:
        """Short demo showing filtering windows events"""
        class MyFrame(wx.Frame, WndProcHookMixin):
            """Demo frame"""
            ...
        
        
    
